<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PackageId>NavierStokesEquations</PackageId>
    <Version>1.0.0</Version>
    <Authors>LUCHER4321</Authors>
    <Description>N-dimensional incompressible fluid simulator based on the Navier-Stokes equations.</Description>
    <PackageTags>physics;simulation;navier-stokes;fluid-dynamics;tensor</PackageTags>
    <RepositoryUrl>https://github.com/LUCHER4321/navier-stokes-equations</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
